services:
    overseerr-auto-request:
        build: .
        container_name: overseerr-auto-request
        hostname: overseerr-auto-request
        restart: unless-stopped
        environment:
            EMAIL: ${EMAIL:-user@example.com}
            PASSWORD: ${PASSWORD:-mysecretpassword}
            OVERSEERR_URL: ${OVERSEERR_URL:-https://example.com}
            MOVIES: ${MOVIES:-1,2,3}
            SHOWS: ${SHOWS:-9,8,7}
            DEBOUNCE_SECONDS: ${DEBOUNCE_SECONDS:-300}
