name: Build

on:
    push:
    pull_request:
        branches: ["main"]
    workflow_call:

permissions:
    contents: read

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: haskell-actions/setup@v2
              with:
                  ghc-version: "9.6.6"
                  cabal-version: "3.14"
            - name: Cache
              uses: actions/cache@v3
              env:
                  cache-name: cache-cabal
              with:
                  path: ~/.cabal
                  key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
                  restore-keys: |
                      ${{ runner.os }}-build-${{ env.cache-name }}-
                      ${{ runner.os }}-build-
                      ${{ runner.os }}-
            - name: Build dependencies
              run: cabal update && cabal build --only-dependencies
            - name: Build
              run: cabal build all
